packages:
  - backend
  - webapp
  - shared
allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@sentry/cli': true
  esbuild: true
  node: true
  prisma: true
  unrs-resolver: true
