extends:
  - react-app # Базовый набор правил для приложений на React
  - ../.eslintrc.yml # Подключение дополнительных правил из общего конфигурационного файла .eslintrc.yml

parserOptions:
  project: ./tsconfig.app.json
  # Указываем основной файл конфигурации TypeScript

  # Запрет на использование console, за исключением указанных методов
  no-console:
    - error
    - allow:
        - info # Разрешен console.info
        - error # Разрешен console.error
        - warn # Разрешен console.warn

overrides:
  - files:
      - vite.config.ts # Применяем отдельные правила для файла конфигурации Vite
    parserOptions:
      project: ./tsconfig.node.json # Для этих файлов используется другая конфигурация TypeScript
rules:
  '@typescript-eslint/no-restricted-imports':
    - error
    - patterns:
        - group:
            - '@ideanick/backend/**'
            - '!@ideanick/backend/**/'
            - '!@ideanick/backend/**/input'
            - '!@ideanick/backend/src/utils/can'
          allowTypeImports: true
          message: 'Only types and input schemas are allowed to be imported from backend workspace'
